# Generated by Django 5.0.1 on 2024-01-11 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('sender', models.CharField(max_length=255)),
                ('ref_number', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('address_date', models.DateField()),
                ('remarks', models.CharField(max_length=255)),
                ('file_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recApp.filesmodel')),
            ],
        ),
    ]
