# Generated by Django 5.0.1 on 2024-02-06 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, unique=True, verbose_name='attachment name')),
                ('category', models.CharField(max_length=156, verbose_name='attachment category')),
                ('ref_number', models.CharField(max_length=156, verbose_name='reference number')),
            ],
        ),
        migrations.CreateModel(
            name='OutGoingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sender', models.CharField(max_length=156, verbose_name='name of the sender')),
                ('ref_number', models.CharField(max_length=156, verbose_name='reference number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('mail_destination', models.CharField(max_length=156, verbose_name='receiver')),
                ('collected_by', models.CharField(max_length=156, verbose_name='collected by')),
                ('date_of_collection', models.DateField(verbose_name='date of collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sender', models.CharField(max_length=156, verbose_name='name of the sender')),
                ('ref_number', models.CharField(max_length=156, verbose_name='reference number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('address_date', models.DateField(blank=True, null=True, verbose_name='address date')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='remarks')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recApp.baseattachments', to_field='name')),
            ],
            options={
                'verbose_name_plural': 'Incoming Mails',
                'ordering': ['-id'],
            },
        ),
    ]
