# Generated by Django 5.0.1 on 2024-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmail',
            name='description',
            field=models.CharField(default='received', max_length=156, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outgoingmail',
            name='description',
            field=models.CharField(default='processed', max_length=156, verbose_name='description'),
            preserve_default=False,
        ),
    ]
