# Generated by Django 5.0.1 on 2024-02-22 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0002_alter_incomingmail_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseattachments',
            name='ref_number',
            field=models.CharField(max_length=156, unique=True, verbose_name='reference number'),
        ),
        migrations.CreateModel(
            name='FileMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_folio', models.CharField(max_length=156)),
                ('collected_by', models.CharField(max_length=156)),
                ('destination_office', models.CharField(max_length=156)),
                ('date_of_collection', models.DateField(verbose_name='date of collection')),
                ('remarks', models.CharField(max_length=156)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file name +', to='recApp.baseattachments', to_field='name')),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file Ref. Number +', to='recApp.baseattachments', to_field='ref_number')),
            ],
        ),
    ]
