# Generated by Django 5.0.1 on 2024-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0002_searchmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('mail_sender', models.CharField(max_length=255)),
                ('mail_receiver', models.CharField(max_length=255)),
                ('ref_number', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('collected_by', models.CharField(max_length=255)),
                ('collecting_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='SearchModel',
        ),
    ]
