# Generated by Django 5.0.1 on 2024-01-25 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recApp', '0003_outgoingmodel_delete_searchmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='filesmodel',
            name='file_category',
            field=models.CharField(default='finance', max_length=255),
        ),
        migrations.AddField(
            model_name='filesmodel',
            name='file_name',
            field=models.CharField(default='transportfinance', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='filesmodel',
            name='file_ref_number',
            field=models.CharField(default='fin/02', max_length=255),
        ),
        # migrations.AlterField(
        #     model_name='recmodel',
        #     name='file_to',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recApp.filesmodel', to_field='file_name'),
        # ),
    ]
